name: Foundation CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        node-version: [16.x, 17.x, 18.x, 20.x]
    steps:
      - uses: actions/checkout@v2
      - name: Test Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
          node-version: ${{ matrix.node-version }}
      - run: sudo apt-get install build-essential libsodium-dev libboost-system-dev
      - run: npm install
      - run: node-gyp clean
      - run: node-gyp configure
      - run: node-gyp build
      - run: npm test
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Save Coverage Checks
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: sudo apt-get install build-essential libsodium-dev libboost-system-dev
      - run: npm install && npm install -g codecov
      - run: npm run test && codecov
